[project]
name = "dmd"
version = "0.0.1"
description = ""
authors = [
    {name = "mukappalambda",email = "maokailan24@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy (>=1.25)",
    "pandas (>=2.0)",
    "matplotlib (>=3.8.0)"
]

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pylint>=4.0.5",
    "pyright>=1.1.408",
    "ruff>=0.15.5",
]

[tool.uv.build-backend]
module-root = ""
