name: Ruff
on: [push]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "./dmd"
          version: 0.5.5
      - uses: chartboost/ruff-action@v1
        with:
          src: "./dmd"
          version: 0.5.5
          args: "format --check"
          changed-files: "true"
